#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2

if [[ "$EUID" = "0" ]]; then
	echo -e "\e[00;31mERROR: NO debe ser root.\e[00m"
	exit 1
fi

clear
docker buildx create --name container-builder --driver docker-container --bootstrap --use
docker buildx build --platform linux/arm64,linux/amd64 --push -t sinfallas/base-node-ionic:20 --builder=container-builder -f Dockerfile20 .
docker buildx build --platform linux/arm64,linux/amd64 --push -t sinfallas/base-node-ionic:22 --builder=container-builder -f Dockerfile22 .
docker buildx build --platform linux/arm64,linux/amd64 --push -t sinfallas/base-node-ionic:23 --builder=container-builder -f Dockerfile23 .
docker buildx build --platform linux/arm64,linux/amd64 --push -t sinfallas/base-node-ionic:24 --builder=container-builder -f Dockerfile24 .
docker buildx build --platform linux/arm64,linux/amd64 --push -t sinfallas/base-node-ionic:25 --builder=container-builder -f Dockerfile25 .
docker buildx build --platform linux/arm64,linux/amd64 --push -t sinfallas/base-node-ionic:latest --builder=container-builder -f Dockerfile25 .
docker buildx rm container-builder
docker system prune -af

echo "finalizado..."
exit 0
